services:
  - type: web
    name: sennin-tube-plus
    env: docker
    plan: free
    region: singapore
    healthCheckPath: /healthz
    dockerCommand: sh -c "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
